default: &default
  is_ows_trial: no
  case_cohort: no
  use_ensemble_sl: no
  

moderna_boost: &moderna_boost
  study_name: COVEBoost
  data_cleaned: /trials/covpn/p3001/analysis/correlates/Part_C_Unblinded_Phase_Data/adata/moderna_boost_data_processed.csv
  assay_metadata: /trials/covpn/p3001/analysis/correlates/Part_C_Unblinded_Phase_Data/adata/assay_metadata.csv
  sampling_scheme: case_control
  covariates: ~.+ MinorityInd + HighRiskInd + risk_score
  ve_ylim: [0,1]
  ve_ylim_log: [0.0,0.98]
  low_efficacy: no
  num_boot_replicates: 1000
  num_perm_replicates: 10000
  ph1: [ph1.BD29]
  endpoints: [EventIndOmicron]

