default: &default
  case_cohort: no
  use_ensemble_sl: no
  

moderna_boost: &moderna_boost
  study_name: COVEBoost
  txt.endpoint: COVID
  # use the mock data temporarily
  data_cleaned: /trials/covpn/p3001/analysis/correlates/Part_C_Unblinded_Phase_Data/adata/mock_moderna_boost_data_processed.csv
  assay_metadata: assay_metadata/moderna_boost_assay_metadata.csv
  sampling_scheme: case_control
  covariates: ~.+ MinorityInd + HighRiskInd + risk_score
  ve_ylim: [0,1]
  ve_ylim_log: [0.0,0.98]
  low_efficacy: no
  num_boot_replicates: 1000
  num_perm_replicates: 10000
  ph1: [ph1.BD29]
  endpoints: [EventIndOmicron]
  txt.coxph.note2: No. at-risk = estimated number in the population for analysis, i.e. baseline negative per-protocol vaccine recipients not experiencing the COVID endpoint or infected through 6 days post BD29 visit; no. cases = number of this cohort with an observed COVID endpoint.

